#!/bin/bash
#
# chkconfig: 2345 96 4
# description: Scientific repository web app
#

### BEGIN INIT INFO
# Provides: sirepo
# Required-Start: rabbitmq celery-sirepo
# Required-Stop: rabbitmq celery-sirepo
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: Enable sirepo
# Description: Daemon for sirepo
### END INIT INFO

bivio_service_name=sirepo

. /etc/init.d/bivio-service.functions
